baseURL = "/"
languageCode = "fr-fr"
paginate = 6
theme = "atlanticvet-theme"
title = "AtlanticVet | Travaillons ensemble pour la santé et le bien-être de vos compagnons"
# Main Menu
[[menu.main]]
name = "E-carnet"
url = "ecarnet/myvetapps"
weight = 1
[[menu.main]]
name = "Infos pratiques"
url = "#service"
weight = 2
[[menu.main]]
name = "Galerie"
url = "#galerie"
weight = 3
[[menu.main]]
name = "Urgences"
url = "#emergency"
weight = 4
[[menu.main]]
name = "Spécialités"
url = "#specialites"
weight = 5
[[menu.main]]
name = "Equipe"
url = "equipe/atlanticvet"
weight = 6
[[menu.main]]
name = "Tarifs"
url = "tarifs/niort-benet"
weight = 7
[[menu.main]]
name = "Contact"
url = "contact"
weight = 8

# Sitemap Menu
[[menu.sitemap]]
name = "E-carnet"
url = "ecarnet/myvetapps"
weight = 1
[[menu.sitemap]]
name = "Infos pratiques"
url = "/#service"
weight = 2
[[menu.sitemap]]
name = "Urgences"
url = "/##emergency"
weight = 3
[[menu.sitemap]]
name = "Tarifs"
url = "tarifs/niort-benet"
weight = 4
[[menu.sitemap]]
name = "Contact"
url = "contact"
weight = 5

[[menu.sitemap]]
name = "Mentions"
url = "mentions"
weight = 6

[params]
blogPageURL = "blog"
contactLink = "contact"
contactTel = "0549734861"
copyright = "Tous droits réservés © Florent FREMONT 2021"
footerLogo = "images/mini-logo-blanc.png"
description = "Travaillons ensemble pour la santé et le bien-être de vos compagnons"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/logo.png"


[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-facebook-official"
url = "https://www.facebook.com/atlanticvetniortetbenet/"
weight = 1

